feat(slack): Add check function for no-bot channel.
BURG3R5/github-slack-bot pull request #136
Opened 2022-11-29 16:42 UTC by Ayush0Chaudhary

Fixes #123

2022-11-30 09:35 UTC, BURG3R5 requested changes
There's a lot of problems with this. First fix the things I mentioned in the comments, then I'll tell you what else is wrong

2022-11-30 09:35 UTC, BURG3R5 commented on bot/slack/runner.py
> +    def __init__(self, token: str, logger: Logger, r):
Remove this `, r`

2022-11-30 09:35 UTC, BURG3R5 commented on bot/slack/__init__.py
> +        Runner.__init__(self, token, logger, bot_id)
`bot_id` is not required

2022-11-30 09:35 UTC, BURG3R5 commented on bot/slack/runner.py
> +        subscriptions = self.storage.get_subscriptions(current=current_channel)
??? Did you even test this?

2022-11-30 09:35 UTC, BURG3R5 commented on bot/slack/runner.py
> +        subscriptions = self.storage.get_subscriptions(current=current_channel)
`current` is NOT an argument of `get_subscriptions`; use `channel=`

2022-11-30 09:35 UTC, BURG3R5 commented on bot/slack/runner.py
> +                f"SlackApiError {E} Failed to fetch conversation info for #{current_channel}"
`current_channel` already has the `"#"` in it, no need to add another

2022-12-21 12:53 UTC, Ayush0Chaudhary commented
will test it by tomorrow eod

2022-12-24 08:42 UTC, closed without merging