feat: Convert to Flask server.
BURG3R5/github-slack-bot pull request #149
Opened 2022-12-21 07:57 UTC by Magnesium12

fixes #148

2022-12-21 08:03 UTC, Magnesium12 commented
I have also updated sentry_sdk to latest version in requirements

2022-12-24 13:28 UTC, BURG3R5 requested changes
Refer to comments for suggested changes

2022-12-24 13:28 UTC, BURG3R5 commented on main.py
>  def test_get() -> str:
Move this route to a new file `bot/views.py` using [this](https://stackoverflow.com/a/60441931)

2022-12-24 13:28 UTC, BURG3R5 commented on main.py
> +@app.route("/", methods=['POST'])
Delete this route

2022-12-24 13:28 UTC, BURG3R5 commented on main.py
> +    return make_response("Correct Payload URI", 200)
Check if this is really necessary. I think if there's no `return` statement, it will still automatically return `200`.

2022-12-24 13:28 UTC, BURG3R5 commented on main.py
> +    return make_response("Correct Payload URI", 200)
Remove this line and test the server. If it doesn't work, only then keep this here.

2022-12-25 15:46 UTC, Magnesium12 commented on main.py
> +    return make_response("Correct Payload URI", 200)
Without this return statement, flask is throwing (and responding with) the error: `TypeError: The view function for 'manage_github_events' did not return a valid response. The function either returned None or ended without a return statement.`
Also on returning something else like `True`, it throws: `TypeError: The view function did not return a valid response. The return type must be a string, dict, list, tuple with headers or status, Response instance, or WSGI callable, but it was a bool.`.
So, if we must return something then I think we should return this `Response` object.

2022-12-26 14:45 UTC, BURG3R5 submitted a review, later dismissed

2022-12-26 15:04 UTC, BURG3R5 requested changes
Needs to be tested

2023-01-05 16:17 UTC, Magnesium12 commented
I have tested it and it can be merged.

2023-01-06 17:14 UTC, merged