feat(slack): Add check function for no-bot channel.
BURG3R5/github-slack-bot pull request #156
Opened 2022-12-24 08:50 UTC by Ayush0Chaudhary

2022-12-24 14:06 UTC, BURG3R5 requested changes
Check comments for details

2022-12-24 14:06 UTC, BURG3R5 commented on bot/slack/runner.py
> +            }
Prettify this by using [this](https://github.com/BURG3R5/github-slack-bot/blob/5dd965c200ba2c982a98048e41a83b77198265fe/main.py#L91-L105) format and sectioning

2022-12-24 14:06 UTC, BURG3R5 commented on bot/slack/runner.py
> +        self.client = WebClient(token=token)
Remove the `client` from here and `Messenger` and instead initialize it in `SlackBotBase` so it can be used in both places

2022-12-27 15:36 UTC, Ayush0Chaudhary commented
will do it by tomorrow 3am.

2022-12-28 07:14 UTC, BURG3R5 approved these changes

2022-12-28 07:24 UTC, BURG3R5 approved these changes

2022-12-28 07:26 UTC, merged