feat: Store mapping from slack user-id to github user-name.
BURG3R5/github-slack-bot pull request #158
Opened 2022-12-24 18:42 UTC by Magnesium12

fixes #155

2022-12-24 19:27 UTC, BURG3R5 requested changes
@Magnesium12

2022-12-24 19:27 UTC, BURG3R5 commented on bot/slack/runner.py
> +        slack_user_id: str = json["user_id"]
Remove the `slack_` prefix from here, it's not necessary

2022-12-24 19:27 UTC, BURG3R5 commented on bot/storage/secrets.py
> +        user: User = User\
The ": User" part is redundant here. We're already supplying the type through the `.get_or_none` method itself.

2022-12-24 19:27 UTC, BURG3R5 commented on bot/storage/secrets.py
> +    :keyword slack_user_id: Unique identifier for Slack user-id."
Remove quote at the end

2022-12-24 19:27 UTC, BURG3R5 commented on bot/storage/secrets.py
> +        return f"{self.github_user_name} ({self.slack_user_id})"
```suggestion
        return f"{self.github_user_name} - {self.slack_user_id}"
```

2022-12-24 19:27 UTC, BURG3R5 commented on main.py
> +                                      request.params.get("slack_user_id"))
See if there's a way you can just pass the query string directly instead of these two string, since we're just passing that string as `state` anyway in `redirect_to_oauth_flow`

2022-12-24 19:27 UTC, BURG3R5 commented on main.py
> +                                      state=request.params.get("state"))
Add a trailing comma and format this like the old code was

2022-12-24 19:27 UTC, BURG3R5 commented on bot/github/authenticator.py
> +    def use_token_for_user_name(self, token: str) -> str | None:
Did you check if we have enough scope to get the username? Or do we have to add some scopes?

2022-12-25 06:59 UTC, Magnesium12 commented on bot/github/authenticator.py
> +    def use_token_for_user_name(self, token: str) -> str | None:
yes, since username is public info, so we can access it with any scope.

2022-12-25 14:14 UTC, BURG3R5 approved these changes

2022-12-25 14:30 UTC, BURG3R5 submitted a review, later dismissed

2022-12-25 14:48 UTC, BURG3R5 approved these changes

2022-12-25 14:49 UTC, merged